### ISSUE TITLE
Incorrect Image dimension 

### ISSUE THREAD

**Issue by jchaudhary21** [atom-robotics-lab/wiki#20]
The dimension of certain images is quite large. Especially in the section "know your tools " of atom wiki, which make the appearance of the whole page a bit odd.  
 Eg . 1. Git logo - atom wiki < know your tools < Git
        2. Linux logo  - atom wiki < know your tools < Linux
        3. Missing logo / link  - atom wiki < know your tools < python

**Comment by 16-17** [comment]
solved by manan
