### ISSUE TITLE
removing ros website's iframe from 'intro to ros' page

### ISSUE THREAD

**Issue by Kartik9250** [atom-robotics-lab/wiki#35]

**Comment by iamdestinychild** [comment]
i would love to take on this task but it has no description so I have some questions

**Comment by Kartik9250** [comment]
Sure @iamdestinychild I've assigned you the issue.

There are few iframe on the site which should be removed. Those iframes could be found on:
- Intro to ROS
- What is ROS, inside Intro to ROS section

**Comment by iamdestinychild** [comment]
ok, I just have to remove them from the code. got it.

**Comment by iamdestinychild** [comment]
I have created a pull request for this task please check it out

**Comment by Kartik9250** [comment]
@iamdestinychild Awesome, Merged the PR
