### ISSUE TITLE
Fixing sphinx url in the `readme.md`

### ISSUE THREAD

**Issue by Kartik9250** [atom-robotics-lab/wiki#37]
Urls of the following need to be corrected in the `readme.md`
- contributing.md's link in "project description" and "about the project"
- wiki's link in the "Acknowledgement" section
- sphinx's link in the badge at "built with" section

**Comment by RJ025** [comment]
hey @Kartik9250  could you please assign this issue to me.

**Comment by Kartik9250** [comment]
@RJ025 @iamdestinychild Thanks for showing interest our repository. I have assigned the issue to both you. Will merge the pr of whoever submit the working package at the earliest.

**Comment by iamdestinychild** [comment]
I've sent in a pull request please check it out

**Comment by RJ025** [comment]
hey @Kartik9250 I sent a PR please take a look at it

**Comment by Kartik9250** [comment]
Yes, @RJ025  Ive already merged @iamdestinychild. Thanks for the PR though, maybe you could look through other issues or raise a new one if you find any.
